### ISSUE TITLE
Broken Tests

### ISSUE THREAD

**Issue by TimonPost** [TimonPost/crossterm#112]
Tracking issue to fix broken tests. 

- [x] src/output/test.rs
```rust
error[E0432]: unresolved import `super::WinApiOutput`
 --> src/output/test.rs:1:34
  |
1 | use super::{AnsiOutput, IStdout, WinApiOutput};
  |                                  ^^^^^^^^^^^^ no `WinApiOutput` in `output`. Did you mean to use `AnsiOutput`?
```
- [x] src/crossterm.rs

```

---- src/crossterm.rs - crossterm::Crossterm::color (line 94) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:95:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::color (line 94)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::terminal (line 80) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:81:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::terminal (line 80)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::cursor (line 52) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:53:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::cursor (line 52)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::input (line 66) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:67:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::input (line 66)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- src/crossterm.rs - crossterm::Crossterm (line 11) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:12:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm (line 11)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::paint (line 136) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:138:11
  |
4 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:139:9
  |
5 |     .on(Color::Black)
  |         ^^^^^ use of undeclared type or module `Color`

error[E0425]: cannot find function `style` in this scope
 --> src/crossterm.rs:137:1
  |
3 | style("Some colored text")
  | ^^^^^ not found in this scope

error[E0425]: cannot find value `screen` in this scope
 --> src/crossterm.rs:140:13
  |
6 |     .paint(&screen);
  |             ^^^^^^ not found in this scope

thread 'src/crossterm.rs - crossterm::Crossterm::paint (line 136)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm (line 19) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Screen`
 --> src/crossterm.rs:20:19
  |
4 | let main_screen = Screen::default();
  |                   ^^^^^^ use of undeclared type or module `Screen`

error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:24:20
  |
8 |    let crossterm = Crossterm::new(&alternate_screen.screen);
  |                    ^^^^^^^^^ use of undeclared type or module `Crossterm`

error[E0425]: cannot find value `alternate_screen` in this scope
 --> src/crossterm.rs:24:36
  |
8 |    let crossterm = Crossterm::new(&alternate_screen.screen);
  |                                    ^^^^^^^^^^^^^^^^ help: a local variable with a similar name exists: `alternate_srceen`

thread 'src/crossterm.rs - crossterm::Crossterm (line 19)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::style (line 109) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:110:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:114:11
  |
8 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:115:9
  |
9 |     .on(Color::Black);
  |         ^^^^^ use of undeclared type or module `Color`

thread 'src/crossterm.rs - crossterm::Crossterm::style (line 109)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
```
- [x] src/terminal/test.rs
```
error[E0432]: unresolved import `super::WinApiTerminal`
 --> src/terminal/test.rs:1:38
  |
1 | use super::{AnsiTerminal, ITerminal, WinApiTerminal};
  |                                      ^^^^^^^^^^^^^^ no `WinApiTerminal` in `terminal`. Did you mean to use `AnsiTerminal`?
```

- [x] crossterm_input 
```
error[E0432]: unresolved import `self::crossterm_input::Screen`
 --> examples/input.rs:3:46
  |
3 | use self::crossterm_input::{input, KeyEvent, Screen, TerminalInput};
  |                                              ^^^^^^ no `Screen` in the root

warning: unused import: `Screen`
 --> examples/input.rs:3:46
  |
3 | use self::crossterm_input::{input, KeyEvent, Screen, TerminalInput};
  |                                              ^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `crossterm_input`.

Caused by:
  process didn't exit successfully: `/usr/bin/rustc --edition=2018 --crate-name input examples/input.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=4d1fc7dc0346a755 -C extra-filename=-4d1fc7dc0346a755 --out-dir /home/brain/rpmbuild/BUILD/crossterm_input-0.1.0/target/release/examples -L dependency=/home/brain/rpmbuild/BUILD/crossterm_input-0.1.0/target/release/deps --extern crossterm_input=/home/brain/rpmbuild/BUILD/crossterm_input-0.1.0/target/release/deps/libcrossterm_input-8b65be6987996055.rlib --extern crossterm_utils=/home/brain/rpmbuild/BUILD/crossterm_input-0.1.0/target/release/deps/libcrossterm_utils-ed94da441d1b421a.rlib --extern libc=/home/brain/rpmbuild/BUILD/crossterm_input-0.1.0/target/release/deps/liblibc-8c6feeca2b5c36fc.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
warning: use of deprecated item 'core::str::<impl str>::trim_right_matches': superseded by `trim_end_matches`
   --> src/input/input.rs:110:22
    |
110 |         let len = rv.trim_right_matches(&['\r', '\n'][..]).len();
    |                      ^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(deprecated)] on by default

error[E0433]: failed to resolve: use of undeclared type or module `ClearType`
  --> examples/async_input.rs:72:20
   |
72 |     terminal.clear(ClearType::All);
   |                    ^^^^^^^^^ use of undeclared type or module `ClearType`

error[E0433]: failed to resolve: use of undeclared type or module `ClearType`
  --> examples/async_input.rs:77:24
   |
77 |         terminal.clear(ClearType::All);
   |                        ^^^^^^^^^ use of undeclared type or module `ClearType`

error[E0433]: failed to resolve: use of undeclared type or module `Screen`
  --> examples/async_input.rs:97:18
   |
97 |     let screen = Screen::new(false);
   |                  ^^^^^^ use of undeclared type or module `Screen`

error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
   --> examples/async_input.rs:101:25
    |
101 |         let crossterm = Crossterm::from_screen(&alternate.screen);
    |                         ^^^^^^^^^ use of undeclared type or module `Crossterm`

error[E0433]: failed to resolve: use of undeclared type or module `ClearType`
   --> examples/async_input.rs:112:28
    |
112 |             terminal.clear(ClearType::All);
    |                            ^^^^^^^^^ use of undeclared type or module `ClearType`

error[E0425]: cannot find value `terminal` in this scope
  --> examples/async_input.rs:72:5
   |
72 |     terminal.clear(ClearType::All);
   |     ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `cursor` in this scope
  --> examples/async_input.rs:73:5
   |
73 |     cursor.goto(1, 1);
   |     ^^^^^^ not found in this scope

error[E0425]: cannot find value `terminal` in this scope
  --> examples/async_input.rs:77:9
   |
77 |         terminal.clear(ClearType::All);
   |         ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `cursor` in this scope
  --> examples/async_input.rs:78:9
   |
78 |         cursor.goto(1, 1);
   |         ^^^^^^ not found in this scope

error[E0425]: cannot find value `terminal` in this scope
  --> examples/async_input.rs:82:9
   |
82 |         terminal.write(format!("{:?}    <- Character pressed", pressed_key));
   |         ^^^^^^^^ not found in this scope
```

# Main not found: 

- [x] style
```
error[E0601]: `main` function not found in crate `style`
  |
  = note: consider adding a `main` function to `examples/style.rs`
```
- [ screen]
```
error[E0601]: `main` function not found in crate `alternate_screen`
  |
  = note: consider adding a `main` function to `examples/alternate_screen.rs`

error[E0601]: `main` function not found in crate `raw_mode`
  |
  = note: consider adding a `main` function to `examples/raw_mode.rs`
```

**Comment by TimonPost** [comment]
Is fixed on refactor branch and will be merged for 0.9

**Comment by TimonPost** [comment]
Fixed in #115

**Comment by ignatenkobrain** [comment]
@TimonPost crossterm_style still fails :(

```rust
error[E0432]: unresolved import `crossterm`
 --> src/macros.rs:124:5
  |
3 | use crossterm::{Clear, Goto, ClearType};
  |     ^^^^^^^^^ maybe a missing `extern crate crossterm;`?
error: cannot find macro `execute!` in this scope
 --> src/macros.rs:130:1
  |
9 | execute!(std::io::stdout(),  Goto(10, 10), Clear(ClearType::CurrentLine));
  | ^^^^^^^
error: cannot find macro `execute!` in this scope
 --> src/macros.rs:127:1
  |
6 | execute!(std::io::stdout(),  Goto(5, 5));
  | ^^^^^^^
error: aborting due to 3 previous errors
For more information about this error, try `rustc --explain E0432`.
thread 'src/macros.rs - execute (line 123)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:319:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- src/macros.rs - queue (line 46) stdout ----
error[E0432]: unresolved import `crossterm`
 --> src/macros.rs:47:5
  |
3 | use crossterm::{queue, Clear, Goto, ClearType};
  |     ^^^^^^^^^ maybe a missing `extern crate crossterm;`?
error: cannot determine resolution for the macro `queue`
 --> src/macros.rs:53:1
  |
9 | queue!(stdout,  Goto(5, 5), Output("5,5".to_string()));
  | ^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0432`.
thread 'src/macros.rs - queue (line 46)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:319:13
failures:
    src/macros.rs - execute (line 123)
    src/macros.rs - queue (line 46)
```

**Comment by ignatenkobrain** [comment]
crossterm_cursor still fails:

```rust
---- cursor::test::goto_ansi stdout ----
thread 'cursor::test::goto_ansi' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `5`', src/cursor/test.rs:62:9
```

**Comment by ignatenkobrain** [comment]
crossterm_style still fails:

```rust
error[E0425]: cannot find function `command` in this scope
   --> examples/style.rs:397:5
    |
397 |     command()
    |     ^^^^^^^ not found in this scope

```

**Comment by ignatenkobrain** [comment]
crossterm_terminal still fails:

```rust
---- terminal::test::resize_ansi stdout ----
thread 'terminal::test::resize_ansi' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `50`', src/terminal/test.rs:34:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by ignatenkobrain** [comment]
crossterm_input still fails:

```rust
error[E0271]: type mismatch resolving `<std::iter::Map<std::str::Bytes<'_>, [closure@src/input/unix_input.rs:490:40: 490:49]> as std::iter::Iterator>::Item == u8`
   --> src/input/unix_input.rs:494:23
    |
494 |         assert_eq!(c, parse_utf8_char(b, bytes).unwrap());
    |                       ^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found u8
    |
    = note: expected type `std::result::Result<u8, _>`
               found type `u8`
note: required by `input::unix_input::parse_utf8_char`
   --> src/input/unix_input.rs:457:1
    |
457 | / fn parse_utf8_char<I>(c: u8, iter: &mut I) -> Result<char>
458 | | where
459 | |     I: Iterator<Item = u8>,
460 | | {
...   |
483 | |     }
484 | | }
    | |_^
```

**Comment by ignatenkobrain** [comment]
@TimonPost any chance to finally fix these?

**Comment by ignatenkobrain** [comment]
Latest crossterm_screen is broken too:

```rust
BUILDSTDERR: error[E0601]: `main` function not found in crate `raw_mode`
BUILDSTDERR:   |
BUILDSTDERR:   = note: consider adding a `main` function to `examples/raw_mode.rs`
BUILDSTDERR: error[E0601]: `main` function not found in crate `alternate_screen`
BUILDSTDERR:   |
BUILDSTDERR:   = note: consider adding a `main` function to `examples/alternate_screen.rs`
```
