### ISSUE TITLE
crossterm tests fail to compile

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#160]
```rust
failures:
---- src/crossterm.rs - crossterm::Crossterm (line 7) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:8:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm (line 7)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/crossterm.rs - crossterm::Crossterm::color (line 65) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:66:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm::color (line 65)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- src/crossterm.rs - crossterm::Crossterm::terminal (line 54) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:55:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm::terminal (line 54)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/crossterm.rs - crossterm::Crossterm::cursor (line 32) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:33:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm::cursor (line 32)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/crossterm.rs - crossterm::Crossterm::input (line 43) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:44:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm::input (line 43)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/crossterm.rs - crossterm::Crossterm::style (line 77) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:78:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:82:11
  |
8 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:83:9
  |
9 |     .on(Color::Black);
  |         ^^^^^ use of undeclared type or module `Color`
error: aborting due to 3 previous errors
BUILDSTDERR: For more information about error: test failed, to rerun pass '--doc'
this error, try `rustc --explain E0433`.
thread 'src/crossterm.rs - crossterm::Crossterm::style (line 77)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
failures:
    src/crossterm.rs - crossterm::Crossterm (line 7)
    src/crossterm.rs - crossterm::Crossterm::color (line 65)
    src/crossterm.rs - crossterm::Crossterm::cursor (line 32)
    src/crossterm.rs - crossterm::Crossterm::input (line 43)
    src/crossterm.rs - crossterm::Crossterm::style (line 77)
    src/crossterm.rs - crossterm::Crossterm::terminal (line 54)
```

**Comment by TimonPost** [comment]
#112
