### ISSUE TITLE
crossterm_style tests fail to compile

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#161]
```rust
failures:
---- src/enums/colored.rs - enums::colored::Colored (line 20) stdout ----
error: expected one of `::`, `;`, or `as`, found `(`
 --> src/enums/colored.rs:21:14
  |
3 | use crossterm(_style)::Colorizer;
  |              ^ expected one of `::`, `;`, or `as` here
error: aborting due to previous error
thread 'src/enums/colored.rs - enums::colored::Colored (line 20)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
---- src/enums/attribute.rs - enums::attribute::Attribute (line 25) stdout ----
error: expected one of `::`, `;`, or `as`, found `(`
 --> src/enums/attribute.rs:26:14
  |
3 | use crossterm(_style)::Colorizer;
  |              ^ expected one of `::`, `;`, or `as` here
error: aborting due to previous error
thread 'src/enums/attribute.rs - enums::attribute::Attribute (line 25)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/traits.rs - traits::Styler (line 55) stdout ----
error: incorrect close delimiter: `}`
 --> src/traits.rs:61:1
  |
2 | fn main() {
  |           - close delimiter possibly meant for this
...
7 | println!("{}", "Negative text".negative();
  |         - un-closed delimiter
8 | }
  | ^ incorrect close delimiter
error: expected token: `,`
 --> src/traits.rs:58:34
  |
5 | println!("{}", "Bold text".bold();
  |                                  ^
error[E0432]: unresolved import `Colorizer`
 --> src/traits.rs:56:5
  |
3 | use Colorizer;
  |     ^^^^^^^^^ no `Colorizer` external crate
error: aborting due to 3 previous errors
For more information about this error, try `rustc --explain E0432`.
thread 'src/traits.rs - traits::Styler (line 55)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/enums/attribute.rs - enums::attribute::Attribute (line 16) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Attribute`
 --> src/enums/attribute.rs:19:5
  |
5 |     Attribute::Underlined,
  |     ^^^^^^^^^ use of undeclared type or module `Attribute`
error[E0433]: failed to resolve: use of undeclared type or module `Attribute`
 --> src/enums/attribute.rs:20:5
  |
6 |     Attribute::NoUnderline
  |     ^^^^^^^^^ use of undeclared type or module `Attribute`
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0433`.
thread 'src/enums/attribute.rs - enums::attribute::Attribute (line 16)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/enums/colored.rs - enums::colored::Colored (line 14) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Colored`
 --> src/enums/colored.rs:15:37
  |
3 | println!("{} Red foreground color", Colored::Fg(Color::Red));
  |                                     ^^^^^^^ use of undeclared type or module `Colored`
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/enums/colored.rs:15:49
  |
3 | println!("{} Red foreground color", Colored::Fg(Color::Red));
  |                                                 ^^^^^ use of undeclared type or module `Color`
error[E0433]: failed to resolve: use of undeclared type or module `Colored`
 --> src/enums/colored.rs:16:38
  |
4 | println!("{} Blue background color", Colored::Bg(Color::Blue));
  |                                      ^^^^^^^ use of undeclared type or module `Colored`
BUILDSTDERR: error[E0433]: failed to resolve: use of undeclared type or module error: test failed, to rerun pass '--doc'
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.bK1ZYt (%check)
`Color`
 --> src/enums/colored.rs:16:50
  |
4 | println!("{} Blue background color", Colored::Bg(Color::Blue));
  |                                                  ^^^^^ use of undeclared type or module `Color`
error: aborting due to 4 previous errors
For more information about this error, try `rustc --explain E0433`.
thread 'src/enums/colored.rs - enums::colored::Colored (line 14)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/traits.rs - traits::Colorize (line 8) stdout ----
error[E0432]: unresolved import `Colorizer`
 --> src/traits.rs:9:5
  |
3 | use Colorizer;
  |     ^^^^^^^^^ no `Colorizer` external crate
error[E0599]: no method named `red` found for type `&'static str` in the current scope
 --> src/traits.rs:11:61
  |
5 | let styled_text = "Red forground color on blue background.".red().on_blue();
  |                                                             ^^^
error: aborting due to 2 previous errors
Some errors occurred: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
thread 'src/traits.rs - traits::Colorize (line 8)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
---- src/lib.rs - style (line 56) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/lib.rs:59:11
  |
5 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/lib.rs:60:9
  |
6 |     .on(Color::Black);
  |         ^^^^^ use of undeclared type or module `Color`
error[E0425]: cannot find function `style` in this scope
 --> src/lib.rs:58:21
  |
4 | let styled_object = style("Some Blue colored text on black background")
  |                     ^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
3 | use crossterm_style::style;
  |
error: aborting due to 3 previous errors
Some errors occurred: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
thread 'src/lib.rs - style (line 56)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:310:13
failures:
    src/enums/attribute.rs - enums::attribute::Attribute (line 16)
    src/enums/attribute.rs - enums::attribute::Attribute (line 25)
    src/enums/colored.rs - enums::colored::Colored (line 14)
    src/enums/colored.rs - enums::colored::Colored (line 20)
    src/lib.rs - style (line 56)
    src/traits.rs - traits::Colorize (line 8)
    src/traits.rs - traits::Styler (line 55)
test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by TimonPost** [comment]
Already open in the other issue: #112
